const M=window.DataModel,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],notes={graph:null,sample:null,correlation:null};
function show(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$('#nav').hidden=id==='welcome'||id==='complete';$$('#nav button').forEach(b=>b.toggleAttribute('aria-current',b.dataset.go===id));scrollTo({top:0,behavior:'smooth'})}
function feedback(id,text,kind=''){$(id).textContent=text;$(id).className='feedback '+kind}
function record(key,text){notes[key]=text;const vals=Object.values(notes).filter(Boolean);$('#notebook').replaceChildren(...(vals.length?vals:['Complete each activity to record an observation.']).map(t=>{const li=document.createElement('li');li.textContent=t;return li}))}
function renderGraph(){let min=Number($('#axis-min').value),max=Number($('#axis-max').value);if(min>=max-2){min=max-3;$('#axis-min').value=min}$('#min-out').textContent=min;$('#max-out').textContent=max;const chart=$('#bar-chart');chart.replaceChildren(...M.graph.map(r=>{const d=document.createElement('div'),height=Math.max(0,Math.min(100,(r.value-min)/(max-min)*100));d.innerHTML='<span class="value">'+r.value+'%</span><i style="height:'+height+'%"></i><b>'+r.month+'</b>';return d}));chart.style.setProperty('--axis-min',min);chart.style.setProperty('--axis-max',max)}
function renderSample(){const n=Number($('#sample-size').value),method=$('#sample-method').value,result=M.summarize(M.sample(n,method)),pct=Math.round(result.rate*100);$('#sample-meter').classList.remove('muted');$('#sample-meter i b').style.width=pct+'%';$('#sample-meter strong').textContent=pct+'%';$('#sample-table').innerHTML=['North','South'].map(g=>'<tr><th>'+g+'</th><td>100</td><td>'+(g==='North'?70:30)+'</td><td>'+result[g].cards+'</td><td>'+result[g].yes+'</td></tr>').join('');const methodText=method==='random'?'Every card had the same chance to be chosen.':'The procedure deliberately recruited 80% from North and 20% from South.';feedback('#sample-feedback',methodText+' This sample is '+pct+'% yes versus the population’s 50%. '+(method==='lobby'?'Increasing this biased sample size does not correct who was overrepresented.':'Random samples can still vary by chance.'),'good');record('sample','Sample: '+methodText+' Result: '+pct+'% yes; population: 50%.');$('#sample-next').disabled=false}
function renderCorrelation(){const view=$('#group-view').value,rows=view==='all'?M.correlation:M.correlation.filter(r=>r.course===view),r=M.corr(rows);$('#corr-stat').textContent=(view==='all'?'Combined':'Within '+view)+': correlation r = '+r.toFixed(2)+'. Correlation describes a pattern; it does not establish cause.';const plot=$('#scatter');plot.replaceChildren(...rows.map(row=>{const p=document.createElement('i');p.className=row.course.toLowerCase();p.style.left=((row.sessions-1)/8*100)+'%';p.style.bottom=((row.score-50)/40*100)+'%';p.title=row.course+': '+row.sessions+' sessions, '+row.score+' points';p.setAttribute('aria-label',p.title);return p}));$('#corr-table').innerHTML=rows.map(row=>'<tr><td>'+row.course+'</td><td>'+row.sessions+'</td><td>'+row.score+'</td></tr>').join('')}
$('#start').onclick=()=>show('graph');$('#reset').onclick=()=>{notes.graph=notes.sample=notes.correlation=null;$('#notebook').innerHTML='<li>Complete each activity to record an observation.</li>';$('#axis-min').value=0;$('#axis-max').value=100;renderGraph();show('welcome')};['axis-min','axis-max'].forEach(id=>$('#'+id).oninput=renderGraph);$('#axis-reset').onclick=()=>{$('#axis-min').value=0;$('#axis-max').value=100;renderGraph()};$('#compare-axis').onclick=()=>{record('graph','Graph: axis limits changed the apparent bar differences, while all six values and the 65.0% mean stayed identical.');feedback('#graph-feedback','Only the rendering changed. Values, months and mean stayed identical. A non-zero axis can be useful for detail when it is clearly labelled and context is preserved.','good');$('#graph-next').disabled=false};$('#graph-next').onclick=()=>show('sample');
$('#draw').onclick=renderSample;$('#sample-hint').onclick=()=>feedback('#sample-feedback','Bias here means the recruitment procedure gives North cards a much greater chance of inclusion. It does not mean every result from the sample is false.','hint');$('#sample-next').onclick=()=>{show('correlation');renderCorrelation()};$('#group-view').onchange=renderCorrelation;$('#corr-hint').onclick=()=>feedback('#corr-feedback','Compare the combined slope with each prior-course group. A pattern can reverse when groups are mixed.','hint');$('#check-corr').onclick=()=>{const answer=$('input[name=corr-answer]:checked');if(!answer){feedback('#corr-feedback','Choose a conclusion first.','hint');return}const good=answer.value==='third';feedback('#corr-feedback',(good?'Supported. ':'Look again after separating the prior-course groups. ')+'The combined association is negative, but each course group trends upward. Prior course is a plausible third variable, and observational correlation alone cannot establish causation.',good?'good':'hint');if(good){record('correlation','Correlation: the combined trend is negative, but both prior-course groups trend upward; association alone does not establish cause.');$('#corr-next').disabled=false}};$('#corr-next').onclick=()=>show('verdict');
$('#check-verdict').onclick=()=>{const good=$('#claim').value==='association'&&$('#support').value==='patterns'&&$('#limit').value==='third';feedback('#verdict-feedback',good?'Evidence-based verdict: the cautious claim matches the combined data, cites the grouped counter-pattern and states the causal limitation.':'Revise one or more parts. Describe association rather than cause, cite both combined and grouped patterns, and name the third-variable/observational limitation.',good?'good':'hint');$('#finish').disabled=!good};$('#finish').onclick=()=>show('complete');$('#again').onclick=()=>$('#reset').click();$$('[data-go]').forEach(b=>b.onclick=()=>{show(b.dataset.go);if(b.dataset.go==='correlation')renderCorrelation()});renderGraph();
const params=new URLSearchParams(location.search),demo=params.get('demo');if(params.get('mobile')==='1')document.documentElement.classList.add('mobile');if(['graph','sample','correlation','verdict','complete'].includes(demo)){show(demo);if(demo==='graph'){$('#axis-min').value=58;$('#axis-max').value=72;renderGraph()}if(demo==='sample')renderSample();if(demo==='correlation')renderCorrelation()}
if(demo)scrollTo(0,0)
