const M=window.TenModel,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={screen:'welcome',sound:true,buildRound:0,buildCount:0,bondRound:0,bondAdded:0,storyRound:0,storyCount:0};
const buildTargets=[4,0,10],bonds=[7,0,5,2,9],stories=[
 {text:'Mina has 3 red apples. A friend brings 2 more. How many apples now?',icon:'🍎',a:3,b:2,op:'+'},
 {text:'Nine birds sit on a fence. Four fly away. How many stay?',icon:'🐦',a:9,b:4,op:'-'},
 {text:'There are 2 shells. You find 6 more. How many shells altogether?',icon:'🐚',a:2,b:6,op:'+'},
 {text:'Ten lanterns glow. Three go dark. How many still glow?',icon:'🏮',a:10,b:3,op:'-'},
 {text:'One bus has 4 riders. Three more get on. How many riders now?',icon:'🚌',a:4,b:3,op:'+'},
 {text:'Six frogs rest by a pond. Six hop away. How many remain?',icon:'🐸',a:6,b:6,op:'-'},
 {text:'A box holds 5 blue blocks and 4 yellow blocks. How many blocks?',icon:'🧱',a:5,b:4,op:'+'}
];
function say(t){if(state.sound&&'speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}}
function show(id){state.screen=id;$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$('#nav').hidden=id==='welcome';$$('#nav button').forEach(b=>b.toggleAttribute('aria-current',b.dataset.go===id));scrollTo({top:0,behavior:'smooth'})}
function tenFrame(count,base=0,onClick){const grid=document.createElement('div');grid.className='ten';grid.setAttribute('role','group');grid.setAttribute('aria-label','Ten-frame with ten slots');for(let i=0;i<10;i++){const b=document.createElement('button');b.className='slot'+(i<count?' filled':'')+(i<base?' base':'');b.setAttribute('aria-label',i<count?'Counter in slot '+(i+1):'Empty slot '+(i+1));b.onclick=()=>onClick?.(i);grid.append(b)}return grid}
function fb(id,t,kind=''){const e=$(id);e.textContent=t;e.className='feedback '+kind}
function renderBuild(){const target=buildTargets[state.buildRound];state.buildCount=state.buildRound===0?0:target===0?2:7;$('#build-target').textContent=target;drawBuild();$('#build-next').disabled=true;fb('#build-feedback',state.buildRound===0?'Demo: tap four empty spaces, or tap filled spaces to remove them.':'Make the numeral and the quantity agree.')}
function drawBuild(){const target=buildTargets[state.buildRound];$('#build-frame').replaceChildren(tenFrame(state.buildCount,0,i=>{state.buildCount=i<state.buildCount?i:Math.min(10,i+1);drawBuild()}));$('#build-equation').textContent=state.buildCount+' counter'+(state.buildCount===1?'':'s')+' · target '+target}
function checkBuild(){const t=buildTargets[state.buildRound];if(state.buildCount===t){fb('#build-feedback',t===0?'Yes. Zero means no counters in the frame.':'Yes — the frame shows '+t+'.','good');$('#build-next').disabled=false;say('Yes. '+t+'.')}else fb('#build-feedback',state.buildCount<t?'You need '+(t-state.buildCount)+' more. Count the empty spaces you will fill.':'There are '+(state.buildCount-t)+' too many. Tap filled spaces to take some away.','hint')}
function renderBond(){const base=bonds[state.bondRound];state.bondAdded=0;$('#bond-prompt').textContent='Start with '+base+'. Fill the empty spaces.';drawBond();$('#bond-next').disabled=true;fb('#bond-feedback',state.bondRound===0?'Seven are already here. Tap Add one three times.':'The blue and gold parts will make one whole ten.')}
function drawBond(){const base=bonds[state.bondRound],total=M.clamp(base+state.bondAdded);$('#bond-frame').replaceChildren(tenFrame(total,base,i=>{if(i>=base)state.bondAdded=i<total?Math.max(0,i-base):Math.min(10-base,i-base+1);drawBond()}));$('#bond-equation').textContent=base+' + '+(state.bondAdded||'?')+' = '+(total===10?'10':'?')}
function checkBond(){const base=bonds[state.bondRound],need=M.complement(base);if(state.bondAdded===need){fb('#bond-feedback',base+' and '+need+' are two parts of ten: '+base+'+'+need+'=10.','good');$('#bond-next').disabled=false}else fb('#bond-feedback',state.bondAdded<need?'Count the empty spaces. Each needs one gold counter.':'Take away gold counters until every slot is filled once.','hint')}
function renderStory(){const s=stories[state.storyRound];state.storyCount=s.a;$('#story-text').textContent=s.text;$('#story-picture').textContent=Array(Math.min(10,s.a)).fill(s.icon).join(' ');$('#story-speak').onclick=()=>say(s.text);drawStory();$('#story-next').disabled=true;fb('#story-feedback',state.storyRound===0?'Start with 3. Add 2 counters to show what arrives.':state.storyRound===stories.length-1?'Fresh challenge: decide what changes and make the result.':'Change the counters to show the story.')}
function drawStory(){const s=stories[state.storyRound];$('#story-frame').replaceChildren(tenFrame(state.storyCount,s.op==='+'?s.a:0,i=>{state.storyCount=i<state.storyCount?i:Math.min(10,i+1);drawStory()}));$('#story-equation').textContent=s.a+' '+s.op+' '+s.b+' = ? · frame shows '+state.storyCount}
function checkStory(){const s=stories[state.storyRound],answer=M.solve(s);if(state.storyCount===answer){$('#story-equation').textContent=M.equation(s);fb('#story-feedback',s.op==='+'?'Yes. Start at '+s.a+' and count on '+s.b+'; you land on '+answer+'.':'Yes. Take '+s.b+' from '+s.a+'; '+answer+' remain.','good');$('#story-next').disabled=false}else fb('#story-feedback',s.op==='+'?'The story adds. Begin at the first number, then count on.':'The story takes away. Begin at the first number, then count back.','hint')}
$('#start').onclick=()=>{show('build');renderBuild();say('Make four. Tap four empty spaces.')};$('#sound').onclick=()=>{state.sound=!state.sound;$('#sound').textContent=state.sound?'🔊 Read aloud':'🔇 Sound off';$('#sound').setAttribute('aria-pressed',String(!state.sound));if(!state.sound&&'speechSynthesis'in window)speechSynthesis.cancel()};$('#reset').onclick=()=>{Object.assign(state,{screen:'welcome',buildRound:0,buildCount:0,bondRound:0,bondAdded:0,storyRound:0,storyCount:0});show('welcome')};
$('#build-hint').onclick=()=>fb('#build-feedback','Count aloud from one while you tap. Stop at '+buildTargets[state.buildRound]+'.','hint');$('#build-check').onclick=checkBuild;$('#build-next').onclick=()=>{if(state.buildRound<buildTargets.length-1){state.buildRound++;renderBuild()}else{show('bonds');renderBond()}};
$('#add').onclick=()=>{const max=10-bonds[state.bondRound];state.bondAdded=Math.min(max,state.bondAdded+1);drawBond()};$('#remove').onclick=()=>{state.bondAdded=Math.max(0,state.bondAdded-1);drawBond()};$('#bond-hint1').onclick=()=>fb('#bond-feedback','Count only the empty spaces.','hint');$('#bond-hint2').onclick=()=>{state.bondAdded=M.complement(bonds[state.bondRound]);drawBond();fb('#bond-feedback','Here is one way: every empty space gets one gold counter. Press Check.','hint')};$('#bond-check').onclick=checkBond;$('#bond-next').onclick=()=>{if(state.bondRound<bonds.length-1){state.bondRound++;renderBond()}else{show('stories');renderStory()}};
$('#story-add').onclick=()=>{state.storyCount=M.clamp(state.storyCount+1);drawStory()};$('#story-remove').onclick=()=>{state.storyCount=M.clamp(state.storyCount-1);drawStory()};$('#story-hint1').onclick=()=>fb('#story-feedback',stories[state.storyRound].op==='+'?'The word “more” means the collection grows.':'The words “away” or “dark” mean the collection gets smaller.','hint');$('#story-hint2').onclick=()=>{const s=stories[state.storyRound];state.storyCount=M.solve(s);drawStory();fb('#story-feedback',s.op==='+'?'Model: start at '+s.a+', then add one '+s.b+' times.':'Model: start at '+s.a+', then remove one '+s.b+' times.','hint')};$('#story-check').onclick=checkStory;$('#story-next').onclick=()=>{if(state.storyRound<stories.length-1){state.storyRound++;renderStory()}else show('finish')};$('#again').onclick=()=>$('#reset').click();
$$('[data-go]').forEach(b=>b.onclick=()=>{show(b.dataset.go);if(b.dataset.go==='build')renderBuild();if(b.dataset.go==='bonds')renderBond();if(b.dataset.go==='stories')renderStory()});$$('[data-say]').forEach(b=>b.onclick=()=>say(b.dataset.say));
const params=new URLSearchParams(location.search),demo=params.get('demo');if(params.get('mobile')==='1')document.documentElement.classList.add('mobile');if(['build','bonds','stories','finish'].includes(demo)){show(demo);if(demo==='build')renderBuild();if(demo==='bonds')renderBond();if(demo==='stories')renderStory()}
