const M=window.GardenModel;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={screen:'welcome',sound:true,matchRound:0,sortRound:0,countRound:0,countTarget:3,revealed:0};
const matchRounds=[{target:'circle',choices:['circle','square'],demo:true},{target:'triangle',choices:['square','triangle','circle']},{target:'square',choices:['triangle','circle','square'],small:true}];
const sortRounds=[{rule:'shape',item:{shape:'triangle',colour:'red'},bins:['triangle','circle']},{rule:'colour',item:{shape:'square',colour:'blue'},bins:['yellow','blue']},{rule:'shape',item:{shape:'circle',colour:'yellow'},bins:['square','circle']}];
const counts=[3,1,2,3];

function say(text){if(!state.sound||!('speechSynthesis' in window))return;speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text));}
function show(id){state.screen=id;$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$('#lesson-nav').hidden=id==='welcome';$$('#lesson-nav button').forEach(b=>b.toggleAttribute('aria-current',b.dataset.go===id));scrollTo({top:0,behavior:'smooth'});}
function shapeEl(name,colour='yellow',small=false){const d=document.createElement('div');d.className=`shape ${name} ${colour}`;d.style.position='relative';if(small)d.style.transform='scale(.75) rotate(18deg)';d.setAttribute('aria-hidden','true');return d;}
function feedback(id,text,type=''){const el=$(id);el.textContent=text;el.className=`feedback ${type}`;}

function renderMatch(){const r=matchRounds[state.matchRound];$('#match-target').replaceChildren(shapeEl(r.target,'yellow',r.small));$('#match-target').setAttribute('aria-label',`Target: ${r.target}`);const box=$('#match-choices');box.replaceChildren();r.choices.forEach(name=>{const b=document.createElement('button');b.className='shape-choice';b.setAttribute('aria-label',name);b.append(shapeEl(name,name==='triangle'?'blue':name==='circle'?'red':'yellow'));b.onclick=()=>chooseMatch(name,b);box.append(b)});$('#match-next').disabled=true;feedback('#match-feedback',r.demo?'The circle is our example. Tap Show me or choose the circle.':'Look at the edges. Which shape stays the same?');}
function chooseMatch(name,button){const r=matchRounds[state.matchRound];if(M.isShapeMatch(r.target,name)){feedback('#match-feedback',`Yes — ${name} matches ${name}!`,'good');say(`Yes. ${name} matches ${name}.`);$('#match-next').disabled=false;$$('#match-choices button').forEach(b=>b.disabled=true);}else{feedback('#match-feedback',name==='circle'?'Feel the round edge. Now look at the target again.':'Count the corners, then try again.','hint');say('Look at the edges, then try again.');button.focus();}}

function renderSort(){const r=sortRounds[state.sortRound];$('#sort-rule').textContent=`Sort by ${r.rule}`;$('#sort-rule-cue').textContent=r.rule==='shape'?'Match the outline. Colour does not decide.':'Match the colour. Shape does not decide.';$('#sort-object').replaceChildren(shapeEl(r.item.shape,r.item.colour));$('#sort-object').setAttribute('aria-label',`${r.item.colour} ${r.item.shape}`);const bins=$('#sort-bins');bins.replaceChildren();r.bins.forEach(key=>{const b=document.createElement('button');b.className='bin';b.dataset.key=key;b.setAttribute('aria-label',`${key} garden`);const symbol=document.createElement('span');symbol.className='bin-symbol';symbol.textContent=r.rule==='shape'?(key==='circle'?'◯':key==='square'?'□':'△'):(key==='blue'?'◆ blue stripes':key==='yellow'?'● yellow dots':'■ red checks');b.append(symbol,document.createTextNode(`${key} garden`));b.onclick=()=>chooseSort(key,b);bins.append(b)});$('#sort-next').disabled=true;feedback('#sort-feedback','Tap a garden. We only use one rule.');}
function chooseSort(key,button){const r=sortRounds[state.sortRound];if(M.belongs(r.item,key,r.rule)){feedback('#sort-feedback',`That works: both are ${key}.`,'good');say(`Yes. Both are ${key}.`);$('#sort-next').disabled=false;$$('#sort-bins button').forEach(b=>b.disabled=true);}else{feedback('#sort-feedback',`We are sorting by ${r.rule}. Look for the matching ${r.rule}.`,'hint');say(`Look for the matching ${r.rule}.`);button.focus();}}

function renderCount(){state.countTarget=counts[state.countRound];state.revealed=0;const f=$('#fireflies');f.replaceChildren();for(let i=0;i<state.countTarget;i++){const d=document.createElement('span');d.className='fly';d.textContent='✦';d.setAttribute('aria-label',`Firefly ${i+1}`);f.append(d)}const choices=$('#count-choices');choices.replaceChildren();[1,2,3].forEach(n=>{const b=document.createElement('button');b.className='jar';b.setAttribute('aria-label',`Jar with ${n} firefl${n===1?'y':'ies'}`);const dots=document.createElement('span');dots.className='jar-dots';for(let i=0;i<n;i++)dots.append(document.createElement('i'));b.append(dots,document.createTextNode(String(n)));b.onclick=()=>chooseCount(n,b);choices.append(b)});$('#count-next').disabled=true;$('#reveal').disabled=false;feedback('#count-feedback','First, show each firefly.');}
function reveal(){if(state.revealed>=state.countTarget)return;const fly=$$('#fireflies .fly')[state.revealed];fly.classList.add('shown');state.revealed++;say(String(state.revealed));feedback('#count-feedback',state.revealed===state.countTarget?`${state.countTarget}! Now choose the matching jar.`:`${state.revealed}… tap again.`,'good');if(state.revealed===state.countTarget)$('#reveal').disabled=true;}
function chooseCount(n,button){if(state.revealed<state.countTarget){feedback('#count-feedback','Show each firefly first so we can count together.','hint');return;}if(M.countChoice(state.countTarget,n)){feedback('#count-feedback',`Yes — ${state.countTarget} firefl${n===1?'y':'ies'} and ${n} in the jar.`,'good');say(`Yes. ${n}.`);$('#count-next').disabled=false;$$('#count-choices button').forEach(b=>b.disabled=true);}else{feedback('#count-feedback','Touch each bright firefly once and count again.','hint');say('Count each bright firefly once.');button.focus();}}

$('#start').onclick=()=>{show('match');renderMatch();say('Find the same shape. The first turn is a circle.')};
$('#sound').onclick=()=>{state.sound=!state.sound;$('#sound').textContent=state.sound?'🔊 Sound on':'🔇 Sound off';$('#sound').setAttribute('aria-pressed',String(!state.sound));if(!state.sound&&'speechSynthesis'in window)speechSynthesis.cancel();};
$('#reset').onclick=()=>{Object.assign(state,{screen:'welcome',matchRound:0,sortRound:0,countRound:0,revealed:0});show('welcome');};
$('#match-demo').onclick=()=>{const right=$$('#match-choices button').find(b=>b.getAttribute('aria-label')===matchRounds[state.matchRound].target);right.classList.add('cued');right.focus();feedback('#match-feedback','See? The outlines are the same. Now tap it.','hint');say('The outlines are the same. Tap this one.');};
$('#match-next').onclick=()=>{if(state.matchRound<2){state.matchRound++;renderMatch()}else{show('sort');renderSort()}};
$('#sort-hint').onclick=()=>{const r=sortRounds[state.sortRound];const right=$$('#sort-bins button').find(b=>M.belongs(r.item,b.dataset.key,r.rule));right.classList.add('cued');right.focus();feedback('#sort-feedback',`This border marks the matching ${r.rule}.`,'hint');};
$('#sort-next').onclick=()=>{if(state.sortRound<2){state.sortRound++;renderSort()}else{show('count');renderCount()}};
$('#reveal').onclick=reveal;$('#count-new').onclick=()=>{state.countRound=(state.countRound+1)%counts.length;renderCount();say('A new firefly group.')};
$('#count-next').onclick=()=>{if(state.countRound<2){state.countRound++;renderCount()}else show('finish')};$('#play-again').onclick=()=>$('#reset').click();
$$('[data-go]').forEach(b=>b.onclick=()=>{const id=b.dataset.go;show(id);if(id==='match')renderMatch();if(id==='sort')renderSort();if(id==='count')renderCount()});
$$('[data-say]').forEach(b=>b.onclick=()=>say(b.dataset.say));
const params=new URLSearchParams(location.search);const preview=params.get('demo');
if(params.get('mobile')==='1')document.documentElement.classList.add('forced-mobile');
if(['match','sort','count','finish'].includes(preview)){show(preview);if(preview==='match')renderMatch();if(preview==='sort')renderSort();if(preview==='count')renderCount();}
