const M=window.ChanceModel,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function show(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$('#nav').hidden=id==='welcome';$$('#nav button').forEach(b=>b.toggleAttribute('aria-current',b.dataset.go===id));scrollTo({top:0,behavior:'smooth'})}
function fb(id,t,k=''){const e=$(id);e.textContent=t;e.className='feedback '+k}
function barRow(label,count,n){const d=document.createElement('div');d.innerHTML='<strong>'+label+'</strong><span><i style="width:'+(count/n*100)+'%"></i></span><b>'+count+' / '+n+'</b>';return d}
function runCoin(n){const pred=$('input[name=coin-pred]:checked');if(!pred){fb('#coin-feedback','Choose a prediction or Skip prediction first.','hint');return}const p=$('#coin-kind').value==='custom'?Number($('#p-heads').value):.5,r=M.coin(n,p);$('#coin-bars').replaceChildren(barRow('Heads',r.heads,n),barRow('Tails',r.tails,n));const rows=[['Heads',r.heads,r.heads/n,p],['Tails',r.tails,r.tails/n,1-p]];$('#coin-table').replaceChildren(...rows.map(x=>{const tr=document.createElement('tr');[x[0],x[1],x[2].toFixed(3),x[3].toFixed(2)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});return tr}));const theory=p===.5?'The fair-coin theory remains 0.50 after any streak.':'This model keeps the theoretical heads probability at '+p.toFixed(2)+' on every trial.';fb('#coin-feedback','Counts sum to '+n+'. This run was '+r.heads+' heads and '+r.tails+' tails. '+theory+' Randomness does not owe the next result.','good');$('#coin-next').disabled=false}
function runDice(){const two=$('#dice-kind').value==='sum',n=Number($('#dice-n').value),r=M.dice(n,two),vals=Object.keys(r.counts).map(Number),max=Math.max(...Object.values(r.counts));const chart=$('#dice-chart');chart.replaceChildren();const body=$('#dice-table');body.replaceChildren();vals.forEach(v=>{const b=document.createElement('div');b.innerHTML='<span style="height:'+(r.counts[v]/max*100)+'%"></span><b>'+v+'</b>';chart.append(b);const tr=document.createElement('tr');[v,r.counts[v],(r.counts[v]/n).toFixed(3),M.diceTheory(v,two).toFixed(3)].forEach(x=>{const td=document.createElement('td');td.textContent=x;tr.append(td)});body.append(tr)});$('#dice-explain').textContent=two?'Sums are not equally likely: 7 has six ordered pairs, while 2 and 12 each have one.':'Each face 1–6 has theoretical probability 1/6.';fb('#dice-feedback','All '+n+' generated outcomes were in '+(two?'2–12':'1–6')+' and the table totals '+n+'. The chart shows this experiment, not fabricated balance.','good');$('#dice-next').disabled=false}
function gameUpdate(simulate=false){const a=Number($('#a-points').value),b=Number($('#b-points').value),g=M.game(a,b);$('#a-out').textContent=a;$('#b-out').textContent=b;let text='Expected A: 0.5 × '+a+' = '+g.a.toFixed(1)+'. Expected B: 0.5 × '+b+' = '+g.b.toFixed(1)+'. '+(g.advantage==='equal'?'The expected advantages are equal.':(g.advantage==='a'?'Side A':'Side B')+' has the greater expected advantage.');if(simulate){const r=M.coin(1000,.5);text+=' Simulation: A '+(r.heads*a)+' points; B '+(r.tails*b)+' points from '+r.n+' flips.'}$('#game-math').textContent=text;fb('#game-feedback','Fairness follows the published probabilities and rewards. One simulation can differ from the expected comparison.','good')}
$('#start').onclick=()=>show('coin');$('#reset').onclick=()=>show('welcome');$('#coin-kind').onchange=()=>$('#p-wrap').hidden=$('#coin-kind').value!=='custom';$('#p-heads').oninput=()=>$('#p-out').textContent=Number($('#p-heads').value).toFixed(2);$$('[data-trials]').forEach(b=>b.onclick=()=>runCoin(Number(b.dataset.trials)));$('#coin-hint').onclick=()=>fb('#coin-feedback','Ten trials have many possible count combinations. More trials often bring a proportion nearer theory, but improvement need not be smooth or exact.','hint');$('#coin-next').onclick=()=>show('dice');
$('#dice-kind').onchange=()=>{$('#dice-explain').textContent=$('#dice-kind').value==='sum'?'A sum can be made in different numbers of ordered pairs.':'Each face 1–6 has theoretical probability 1/6.'};$('#roll').onclick=runDice;$('#dice-hint').onclick=()=>fb('#dice-feedback','For sum 7: 1+6, 2+5, 3+4, 4+3, 5+2, 6+1. For sum 2: only 1+1.','hint');$('#dice-next').onclick=()=>{show('game');gameUpdate()};
['a-points','b-points'].forEach(id=>$('#'+id).oninput=()=>gameUpdate());$('#simulate').onclick=()=>gameUpdate(true);$('#challenge-check').onclick=()=>{const c=$('input[name=challenge]:checked');if(!c){fb('#challenge-feedback','Choose equal, Side A or Side B first.','hint');return}const good=c.value==='b';fb('#challenge-feedback',(good?'Correct. ':'Try the pair counts. ')+'A: 6/36 × 2 = 12/36 expected points. B: 30/36 × 1 = 30/36. Side B has the greater expected advantage.',''+(good?'good':'hint'));if(good)$('#finish-button').disabled=false};$('#finish-button').onclick=()=>show('finish');$('#again').onclick=()=>$('#reset').click();$$('[data-go]').forEach(b=>b.onclick=()=>{show(b.dataset.go);if(b.dataset.go==='game')gameUpdate()});
const params=new URLSearchParams(location.search),demo=params.get('demo');if(params.get('mobile')==='1')document.documentElement.classList.add('mobile');if(['coin','dice','game','finish'].includes(demo)){show(demo);if(demo==='coin'){$('input[name=coin-pred][value=skip]').checked=true;runCoin(100)}if(demo==='dice'){$('#dice-kind').value='sum';runDice()}if(demo==='game')gameUpdate()}
