const M=window.EcoModel,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const organisms=[['grass','🌾','Meadow grass','producer'],['clover','☘️','Red clover','producer'],['rabbit','🐇','Rabbit','herbivore'],['grasshopper','🦗','Grasshopper','herbivore'],['fox','🦊','Red fox','predator'],['cactus','🌵','Desert cactus','different habitat'],['dolphin','🐬','Dolphin','different habitat']];
const scenarios={healthy:{water:7,light:7,grass:7,flowers:7,rabbits:4,grasshoppers:4,foxes:3},dry:{water:2,light:8,grass:6,flowers:6,rabbits:5,grasshoppers:4,foxes:3},shade:{water:8,light:2,grass:6,flowers:6,rabbits:4,grasshoppers:5,foxes:3}};
let exp,expStart,expStep=0,restore,restoreStep=0,selected=[];
function show(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$('#nav').hidden=id==='welcome';$$('#nav button').forEach(b=>b.toggleAttribute('aria-current',b.dataset.go===id));scrollTo({top:0,behavior:'smooth'})}
function fb(id,t,k=''){const e=$(id);e.textContent=t;e.className='feedback '+k}
function renderOrganisms(){const box=$('#organisms');box.replaceChildren();organisms.forEach(o=>{const l=document.createElement('label');l.className='organism';const c=document.createElement('input');c.type='checkbox';c.value=o[0];c.onchange=()=>{selected=$$('#organisms input:checked').map(x=>x.value);renderWeb()};l.append(c,document.createTextNode(o[1]+' '+o[2]));const sm=document.createElement('small');sm.textContent=o[3];l.append(sm);box.append(l)});renderWeb()}
function renderWeb(){const has=x=>selected.includes(x),parts=[];if(has('grass'))parts.push('☀ + water → grass');if(has('clover'))parts.push('☀ + water → clover');if(has('rabbit')&&(has('grass')||has('clover')))parts.push('plants → rabbit');if(has('grasshopper')&&(has('grass')||has('clover')))parts.push('plants → grasshopper');if(has('fox')&&(has('rabbit')||has('grasshopper')))parts.push('rabbit / grasshopper → fox');$('#food-web').textContent=parts.length?parts.join('  •  '):'Select organisms to reveal energy paths.'}
function loadScenario(name){exp={...scenarios[name]};expStart={...exp};expStep=0;$('#water').value=exp.water;$('#light').value=exp.light;syncControls();$('#history').replaceChildren();addHistory();renderIndicators('#indicators',exp);$('#exp-next').disabled=true;$$('input[name=prediction]').forEach(x=>x.checked=false);fb('#exp-feedback','Choose a prediction, then advance exactly one inspectable step.')}
function syncControls(){$('#water-out').textContent=$('#water').value;$('#light-out').textContent=$('#light').value;$('#r-water-out').textContent=$('#r-water').value;$('#r-light-out').textContent=$('#r-light').value}
function renderIndicators(target,s){const box=$(target);box.replaceChildren();[['Grass',s.grass],['Flowers',s.flowers],['Rabbits',s.rabbits],['Grasshoppers',s.grasshoppers],['Foxes',s.foxes]].forEach(([n,v])=>{const d=document.createElement('div');d.innerHTML='<strong>'+n+'</strong><span aria-label="'+n+' '+v+' out of 10"><i style="width:'+v*10+'%"></i></span><b>'+v+'</b>';box.append(d)})}
function addHistory(){const tr=document.createElement('tr');[expStep,exp.grass,exp.flowers,exp.rabbits,exp.grasshoppers,exp.foxes].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});$('#history').append(tr)}
function stepExperiment(){const pred=$('input[name=prediction]:checked');if(!pred){fb('#exp-feedback','Choose increase, stay about the same, or decrease first.','hint');return}exp.water=Number($('#water').value);exp.light=Number($('#light').value);const before={...exp};exp=M.step(exp);expStep++;addHistory();renderIndicators('#indicators',exp);const trend=M.plantTrend(before,exp),match=pred.value===trend;fb('#exp-feedback',(match?'Your prediction matched this model step. ':'This step differed from your prediction. ')+(trend==='up'?'Plant values increased because resource-driven growth exceeded eating.':trend==='down'?'Plant values decreased because low resources and eating outweighed growth.':'Plant values stayed close because growth and eating nearly balanced.')+' A larger biased change is not guaranteed in every real meadow.',match?'good':'hint');$('#exp-next').disabled=false}
function resetRestore(){restore={water:1,light:8,grass:2,flowers:2,rabbits:8,grasshoppers:4,foxes:0};restoreStep=0;$('#r-water').value=1;$('#r-light').value=8;$('#r-clover').checked=true;$('#r-fox').checked=false;syncControls();$('#log').replaceChildren();renderIndicators('#restore-indicators',restore);$('#finish-button').disabled=true;fb('#restore-feedback','Diagnosis: scarce water limits plants while many rabbits eat grass. Choose a change, then inspect each step.')}
function stepRestore(){restore.water=Number($('#r-water').value);restore.light=Number($('#r-light').value);if(!$('#r-clover').checked)restore.flowers=0;if($('#r-fox').checked&&restore.foxes===0)restore.foxes=2;const before={...restore};restore=M.step(restore);restoreStep++;renderIndicators('#restore-indicators',restore);const p=document.createElement('p');p.textContent='Step '+restoreStep+': water '+before.water+'; grass '+before.grass+'→'+restore.grass+', rabbits '+before.rabbits+'→'+restore.rabbits+', foxes '+before.foxes+'→'+restore.foxes+'. '+(restore.grass>before.grass?'Plants recovered because resources supported growth.':'Plant recovery is still limited by resources or eating.');$('#log').prepend(p);const stable=restoreStep>=2&&restore.grass>=2.5&&restore.flowers>=2&&restore.rabbits<=8;fb('#restore-feedback',stable?'The bounded model shows a plausible recovery path. It does not promise the same result in nature.':'Keep testing. Water supports plants; food supports consumers; foxes respond to available prey.',stable?'good':'hint');$('#finish-button').disabled=!stable}
$('#start').onclick=()=>{show('build');renderOrganisms();fb('#build-feedback','Healthy example: sunlight and water support grass and clover; herbivores eat plants; the fox depends on prey.')};$('#reset-all').onclick=()=>{selected=[];show('welcome')};$('#build-hint').onclick=()=>fb('#build-feedback','Choose two producers, two plant-eaters and one predator that all belong in a meadow.','hint');$('#build-check').onclick=()=>{if(M.viable(selected)&&!selected.includes('cactus')&&!selected.includes('dolphin')){fb('#build-feedback','Complete path: sunlight + water → producers → herbivores → predator.','good');$('#build-next').disabled=false}else fb('#build-feedback','This team is missing a role or includes an organism from a different habitat. Try again.','hint')};$('#build-next').onclick=()=>{show('experiment');loadScenario('healthy')};
$('#scenario').onchange=e=>loadScenario(e.target.value);['water','light','r-water','r-light'].forEach(id=>$('#'+id).oninput=syncControls);$('#step').onclick=stepExperiment;$('#pause').onclick=()=>{const on=$('#pause').getAttribute('aria-pressed')==='true';$('#pause').setAttribute('aria-pressed',String(!on));$('#pause').textContent=on?'⏸ Paused':'▶ Ready to step'};$('#exp-reset').onclick=()=>loadScenario($('#scenario').value);$('#exp-hint').onclick=()=>fb('#exp-feedback','Plants change first when water or light changes. Herbivores respond through food, then predators through prey.','hint');$('#exp-next').onclick=()=>{show('restore');resetRestore()};
$('#restore-step').onclick=stepRestore;$('#restore-reset').onclick=resetRestore;$('#finish-button').onclick=()=>show('finish');$('#again').onclick=()=>$('#reset-all').click();$$('[data-go]').forEach(b=>b.onclick=()=>{show(b.dataset.go);if(b.dataset.go==='build')renderOrganisms();if(b.dataset.go==='experiment')loadScenario('healthy');if(b.dataset.go==='restore')resetRestore()});
const params=new URLSearchParams(location.search),demo=params.get('demo');if(params.get('mobile')==='1')document.documentElement.classList.add('mobile');if(['build','experiment','restore','finish'].includes(demo)){show(demo);if(demo==='build')renderOrganisms();if(demo==='experiment')loadScenario('healthy');if(demo==='restore')resetRestore()}
